# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PennApps Accelerator
email: sibnerian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  PennApps Accelerator is dedicated to providing services, mentorship, and grants to
  UPenn tech entrepreneurs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://accelerator.pennapps.com" # the base hostname & protocol for your site
twitter_username: sibnerian
github_username:  sibnerian

# Build settings
markdown: kramdown
