# Site settings
title: PennApps Accelerator
email: pennappsaccelerator@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  PennApps Accelerator is dedicated to providing services, mentorship, and grants to
  UPenn tech entrepreneurs.
baseurl: "/accelerator-site" # the subpath of your site, e.g. /blog
url: "http://accelerator.pennapps.com" # the base hostname & protocol for your site
sass:
  sass_dir: .
  style: compressed
exclude: [vendor]
collections:
  teams:
    output: true
    years:
      - Spring 2016
      # - Fall 2015

# Build settings
markdown: kramdown
